5 7 2 (#273)
* WIP BEO-8533

* WIP BEO-8533 support model & manufacturer + Refactor

* WIP BEO-8533

* WIP BEO-8533

* WIP BEO-8533 Rename

* WIP BEO-8533 support list

* WIP BEO-8533 support ids

* WIP BEO-8533 hh device support new fields

* WIP BEO-8533 Validations

* WIP BEO-8533 logs

* WIP BEO-8533 logs

* WIP BEO-8533 fix cast error

* BEO-8533

* BEO-8533

* BEO-8533

* BEO-8533 - extract

* WIP BEO-8607 add event for remote tasks

* WIP BEO-8607 revert docker file

* BEO-8607 handel campaign event by CB and event bus

* BEO-8533 - Model is string again

* BEO-8607

* WIP BEO-8607

* WIP BEO-8607 - No actual change

* WIP BEO-8607 -> BEO-8611

* WIP BEO-8607 - fix compilation error and wip send

* WIP BEO-8607

* WIP BEO-8607

* BEO-8607

* WIP BEO-8607 - Remove Todo(s)

* WIP BEO-8607 - Remove 'send push' from handler

* WIP BEO-8607

* WIP BEO-8607 - Fix compilations

* WIP BEO-8607

* WIP BEO-8607

* WIP BEO-8607 - Update objects by DR

* WIP BEO-8607 - Rename event + Replace event parsed json event

* WIP BEO-8607 - save EventNotificationAction

* WIP BEO-8607 - dispatch & update

* WIP BEO-8607 - Having mapping issue

* WIP BEO-8607 - Add dispatch to controller

* WIP BEO-8607 - Open issue, get partner campaign support status

* WIP BEO-8607 - fix reflection

* wip BEO-8607

* wip BEO-8607

* WIP BEO-8607 - pricing dal, use generic Data set

* wip BEO-8607 change event design

* WIP BEO-8607 - fix compilation, temp* remove event refs

* WIP BEO-8607 - fix compilation, temp* remove event refs

* WIP BEO-8607

* WIP BEO-8607 - Move campaign filters to the RT handler

* WIP BEO-8607 - Working mappings

* WIP BEO-8607 - fix basic flow

* WIP BEO-8607 - fix basic flow

* WIP BEO-8607 - Change according to DR

* no message

* WIP BEO-8607 - Handler

* WIP BEO-8607 - TBD fields

* WIP BEO-8607

* WIP BEO-8607 - new SetState action

* BEO-8607 CAMPAIGN FILTER

* WIP BEO-8607 - fix compilation

* WIP BEO-8607 - fix compilation

* BEO-8607 filtering and trigger conditions

* BEO-8607 filtering and trigger conditions

* WIP BEO-8533 - fix regex expression

* WIP BEO-8533 - fix list

* WIP BEO-8607 crud actions

* WIP BEO-8607 - some Todos done

* WIP BEO-8607 -> BEO-8611 crud actions

* WIP BEO-8607 - udid NotImplementedException, No validation of Manufacturers if exists

* WIP BEO-8607 - Change inbox things

* WIP BEO-8607 - Fix mappings

* WIP BEO-8533 - Fix mappings

* WIP BEO-8533 -Fix cache after delete

* WIP BEO-8533 -Fix regex

* WIP BEO-8533 -Fix type

* WIP BEO-8607 -> BEO-8611 finish crud actions

* WIP BEO-8533 - Add db protection and change error per QA request

* WIP BEO-8533 - revert

* WIP BEO-8533 - init cache on update

* WIP BEO-8607

* WIP BEO-8607 - Working campaign trigger add flow

* WIP BEO-8533 - fail request if has model but no manufacturer:  "message": "Can't add device with model but without manufacturer Id",

* WIP BEO-8607 -> BEO-8613

* WIP BEO-8607 -> finish BEO-8613

* WIP BEO-8607 - TriggerCampaign CRUD

* WIP BEO-8614

* WIP BEO-8533 - BEO-8860

* wip BEO-8616

* wip BEO-8616

* wip BEO-8616

* WIP BEO-8607 - rename methods

* wip BEO-8616

* wip BEO-8616

* WIP BEO-8607 -> BEO-8612

* WIP BEO-8607 - Add get campaign from cache

* WIP BEO-8607 - fix enum type mappings

* WIP BEO-8607 -> BEO-8612 last touches

* WIP BEO-8607 -> BEO-8612 now real finish

* WIP BEO-8607 -> BEO-8614

* WIP BEO-8607 -> BEO-8614 fix mapping

* wip BEO-8616

* WIP BEO-8607 fix client libs and create DynamicList for BEO-8871

* WIP BEO-8607 -> BEO-8871

* BEO-8607 fix list and cache

* wip BEO-8615 new error "CampaignIsAlreadyAppliedForSubscription"

* oops

* fix BEO-8607 -> BEO-8880

* BEO-8607 remove the option to create trigger campaign on UPDATE actions

* BEO-8607 fix list campaigns by none existing ids

* WIP BEO-8607 --> BEO-8879, error: Active {TYPE} campaigns Exceeded Max Size

* WIP BEO-8607

* WIP BEO-8533, pending updates for using manufacturer instead of manufacturerId

* WIP BEO-8607, bug fixes: BEO-8877 + BEO-8884

* WIP BEO-8607 Support KalturaUdidDynamicListCondition

* WIP BEO-8607 Support dynamicList lc and get method

* WIP BEO-8607 -> BEO-8871

* Fix null reference

* fix - https://kaltura.atlassian.net/browse/BEO-8893

* WIP BEO-8607 Push for Merge

* WIP BEO-8607 -> BEO-8884

* WIP BEO-8607 - Fix ValidateStateChange

* WIP BEO-8607 -> BEO-8888

* WIP BEO-8607 -> BEO-8871 set cache methods and list actions

* WIP BEO-8607 -> BEO-8871

* WIP BEO-8607 -> BEO-8897 -> validation for existing of collections

* WIP BEO-8607 -> BEO-8897 -> validation for existing of collections (channel)

* WIP BEO-8607 -> BEO-8887

* WIP BEO-8607 -> BEO-8871 addFromBulkUpload

* WIP BEO-8607 -> BEO-8905

* WIP BEO-8607 -> BEO-8898

* WIP BEO-8607 -> BEO-8871 finish addFromBulkUpload

* WIP BEO-8607 - fix order by and pagination

* BEO-8607 -> fix BEO-8848

* WIP BEO-8607 - Add new Handler to dockerFile

* WIP BEO-8607 -> BEO-8900, replace event object due to FW limitation

* WIP BEO-8607 - Empty

* WIP BEO-8607 - Docker file

* WIP BEO-8607 - Docker file parse error

* channel validation for non-opc

* fix BEO-8918 for BEO-8607

* WIP BEO-8607 - Date condition error

* WIP BEO-8607 - Change log

* fix BEO-8852 for BEO-8607

* fix BEO-8903 for BEO-8607

* fix BEO-8887 for BEO-8607

* calc discout from 0

* fix BEO-8907 for BEO-8607

* BEO-8871 validate for max 5000 udids BEO-8607

* WIP BEO-8607

* wip BEO-8607 allow one time purchase by campaign

* WIP BEO-8607 -> BEO-8914

* WIP BEO-8607 -> BEO-8914 -> Reflactor

* fix BEO-8935 for BEO-8607

* wip

* WIP BEO-8607 -> BEO-8935, if end date smaller than utc now, return as archive

* fix BEO-8935 for BEO-8607

* fix BEO-8941 and BEO-8943 for BEO-8607

* fixget active now campaigns for BEO-8607

* fix BEO-8936 and BEO-8937 for BEO-8871and BEO-8607

* WIP BEO-8533 -> BEO-8938

* WIP BEO-8533 -> BEO-8938, id for internal storage

* WIP BEO-8533 -> BEO-8938 epoch dates

* WIP BEO-8533 -> BEO-8938 Add todo

* WIP BEO-8533 -> BEO-8938 Return manufacturer string

* WIP BEO-8533 -> BEO-8938 Typo

* WIP BEO-8533 -> BEO-8938 Remove comment

* fix BEO-8911 for BEO-8607

* WIP BEO-8533 - Reflection

* WIP BEO-8533 -> BEO-8938 Remove regex name validation

* WIP BEO-8533 -> BEO-8938 CR

* WIP BEO-8607 - Empty commit

* WIP BEO-8607 - Fix broken smoke

* BEO-8607 set one use to campaign for each product

* try to fix BEO-8947 for BEO-8607

* fix BEO-8900 for BEO-8607

* fix - BEO-8971

* WIP BEO-8607 -> BEO-8985

* WIP BEO-8607 - Logs for missing trigger campaign (brand Id > 1)

* WIP BEO-8607 -> BEO-8983

* fix - BEO-9009

* remove data RecurringCampaignDetails

* WIP BEO-8607 -> BEO-9020

* fix BEO-8829 (#263)

Co-authored-by: irayanai <iray@tvinci.com>

* BEO-8999 when purchasing collection with PG set to asyncPolicy = true ProductPrice.List return "COLLECTION_PURCHASED" instead of "PENDING_ENTITLEMENT" (#260)

* BEO-8999  Fix update/delete pendingCollectionTran

* WIP BEO-8607 -> Allow empty trigger campaign

* WIP BEO-8607 -> Check if campaign condition is allowed : Batch + Trigger

* fix - BEO-9015

* WIP 572 -> BEO-9008 + BEO-9010

* fix - BEO-8378 (missing from 5_6_0)

Co-authored-by: Matan Oved <matan.oved@Kaltura.com>
Co-authored-by: shir-bruchim <shirbruchim51@gmail.com>
Co-authored-by: irayanai <iray@tvinci.com>
Co-authored-by: Vladimir Statkevich <Vladimir.Statkevich@kaltura.com>
Co-authored-by: AnatGr <anat.grossberg@kaltura.com>